check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.32.3
  build-stratergy: Source
  registry: quay.io
  registry-org: grpereir
  registry-project: management-api
  registry-secret: grpereir-quay-bot-03-pull-secret
deploy:
  test:
    default-action: "pr"
    project-org: "gregory-pereira"
    project-name: "thoth-application"
    image-name: "management-api"
    overlay-contextpath: "management-api/overlays/test/imagestreamtag.yaml"
  prod:
    default-action: "commit"
    project-org: "gregory-pereira"
    project-name: "thoth-application"
    image-name: "management-api"
    overlay-contextpath: "management-api/overlays/moc-prod/imagestreamtag.yaml"
